spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forumhub?currentSchema=public&stringtype=unspecified
    username: usuario
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: true 
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000ms 

  main:
    allow-bean-definition-overriding: true

jwt:
  issuer: your-issuer
  secret: your-very-secure-secret-key
  expiration: 3600  
cors:
  allowed:
    origins: "http://localhost:4200"  
    methods: GET,POST,PUT,DELETE,OPTIONS

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

rate-limit:
  ip-limit: 10
  user-limit: 10

server:
  port: 8080
